import SwiftUI

struct RootView: View {
 @EnvironmentObject var m:TradingModel
 var body: some View { Group { if m.connected { MainTabs() } else { LoginView() } }.preferredColorScheme(.dark) }
}
struct LoginView:View { @EnvironmentObject var m:TradingModel; var body:some View { VStack(spacing:18){ Spacer(); Image(systemName:"chart.xyaxis.line").font(.system(size:58)); Text("FOREX TRADING V1").font(.title.bold()); Text("PC v2.8.1 · PAPER ONLY").foregroundStyle(.yellow); SecureField("Mobile access token",text:$m.token).textFieldStyle(.roundedBorder).textInputAutocapitalization(.never); Button("Connect"){Task{await m.refresh(); if m.connected {m.connect()}}}.buttonStyle(.borderedProminent); if !m.error.isEmpty {Text(m.error).foregroundStyle(.red)}; Spacer() }.padding() } }
struct MainTabs:View { var body:some View { TabView {
 Dashboard().tabItem{Label("Dashboard",systemImage:"gauge.with.dots.needle.50percent")}
 Markets().tabItem{Label("Markets",systemImage:"chart.bar")}
 Decisions().tabItem{Label("AI Feed",systemImage:"brain")}
 TradesView().tabItem{Label("Trades",systemImage:"list.bullet.rectangle")}
 ShadowView().tabItem{Label("Shadow",systemImage:"waveform.path.ecg")}
 SettingsView().tabItem{Label("Settings",systemImage:"gear")}
} } }
struct Dashboard:View { @EnvironmentObject var m:TradingModel; var s:AppState?{m.state}; var body:some View { NavigationStack{ScrollView{VStack(spacing:14){Text("PAPER ONLY · NEURAL EDGE SHADOW ONLY").font(.caption.bold()).foregroundStyle(.yellow); HStack{Metric("EQUITY",s?.equity);Metric("SESSION P/L",(s?.realized ?? 0)+(s?.unrealized ?? 0))}; Text(s?.status ?? "Connecting…").frame(maxWidth:.infinity,alignment:.leading); HStack{Button(s?.enabled == true ? "AI ACTIVE":"START AI"){Task{await m.control("start")}}; Button("PAUSE"){Task{await m.control("pause")}}}.buttonStyle(.borderedProminent); Text("Open positions \(s?.open_positions ?? 0)/\(s?.max_positions ?? 0)").font(.headline); ForEach(s?.positions ?? []){p in Row(p.symbol,p.side ?? "",p.unrealized ?? p.pnl ?? 0)} }.padding()}.navigationTitle("Forex Trading V1")}.task{m.connect()} } }
struct Metric:View {let t:String;let v:Double?;init(_ t:String,_ v:Double?){self.t=t;self.v=v};var body:some View{VStack{Text(t).font(.caption);Text((v ?? 0).formatted(.currency(code:"USD"))).font(.title3.bold())}.frame(maxWidth:.infinity).padding().background(.thinMaterial).clipShape(RoundedRectangle(cornerRadius:14))}}
struct Row:View{let a:String,b:String;let n:Double?;init(_ a:String,_ b:String,_ n:Double?=nil){self.a=a;self.b=b;self.n=n};var body:some View{HStack{VStack(alignment:.leading){Text(a).bold();Text(b).font(.caption).foregroundStyle(.secondary)};Spacer();if let n{Text(n.formatted(.number.precision(.fractionLength(2))))}}.padding().background(.thinMaterial).clipShape(RoundedRectangle(cornerRadius:12))}}
struct Markets:View{@EnvironmentObject var m:TradingModel;@State private var search="";var body:some View{NavigationStack{List((m.state?.markets ?? []).filter{search.isEmpty || $0.symbol.localizedCaseInsensitiveContains(search) || ($0.name ?? "").localizedCaseInsensitiveContains(search)}){x in VStack(alignment:.leading){Text(x.symbol).bold();Text([x.name,x.category,x.regime].compactMap{$0}.joined(separator:" · ")).font(.caption);Text("\(x.action ?? "WAIT") · \(Int(x.score ?? 0))")}}.searchable(text:$search).navigationTitle("Markets")}}}
struct Decisions:View{@EnvironmentObject var m:TradingModel;var body:some View{NavigationStack{List(m.state?.decisions ?? []){d in VStack(alignment:.leading){Text("\(d.symbol ?? "Market") · \(d.action ?? "WAIT")").bold();Text(d.text ?? d.reason ?? "").font(.caption)}}.navigationTitle("AI Decision Feed")}}}
struct TradesView:View{@EnvironmentObject var m:TradingModel;var body:some View{NavigationStack{List(m.state?.trades ?? []){t in Row(t.symbol ?? "Trade",t.side ?? t.reason ?? "",t.pnl)}.overlay{if (m.state?.trades ?? []).isEmpty{VStack(spacing:8){Image(systemName:"tray").font(.largeTitle);Text("No closed PAPER trades").foregroundStyle(.secondary)}}}.navigationTitle("Trade Log")}}}
struct ShadowView:View{@EnvironmentObject var m:TradingModel;var body:some View{NavigationStack{List{Section("Neural Edge"){LabeledContent("Samples",value:"\(m.state?.shadow?.samples ?? m.state?.shadow?.observations ?? 0)");LabeledContent("Validation",value:m.state?.shadow?.validation_accuracy.map{"\($0)%"} ?? "--");LabeledContent("Shadow P/L",value:(m.state?.shadow?.pnl ?? m.state?.shadow?.shadow_pnl ?? 0).formatted(.currency(code:"USD")))};Section("Safety"){Text("SHADOW ONLY · no broker execution").foregroundStyle(.yellow)}}.navigationTitle("Shadow Lab")}}}
struct SettingsView:View{@EnvironmentObject var m:TradingModel;@State private var confirmClose=false;@State private var capital="20000";@State private var topN=5;var body:some View{NavigationStack{Form{Section("Safety"){Text("100% PAPER ONLY");Text("Neural Edge: SHADOW ONLY");Text("No broker-order endpoint")};Section("Engine"){Text("PC Core: \(m.state?.pc_core_version ?? "2.8.1")");Text("Cloud AI continues when this app is closed.")};Section{Button("Close all PAPER positions",role:.destructive){confirmClose=true}}}.confirmationDialog("Close every open PAPER position?",isPresented:$confirmClose,titleVisibility:.visible){Button("Close all",role:.destructive){Task{await m.control("close_all")}}}.navigationTitle("Settings")}}}
