const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let token=localStorage.getItem('fxai_token')||'', state=null, timer=null;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{'Authorization':`Bearer ${token}`,'Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok)throw new Error(r.status===401?'Wrong access token':`Cloud error ${r.status}`);return r.json()}
function marketCard(m,reason=true){let action=(m.action||'WAIT').toLowerCase();return `<article class="market"><div><div class="symbol">${esc(m.symbol)}</div><div class="name">${esc(m.name)} · ${esc(m.category)} · RSI ${Number(m.rsi).toFixed(1)}</div></div><div class="score"><b class="${action}">${esc(m.action)}</b><small>${Number(m.score).toFixed(0)} SCORE</small></div>${reason?`<div class="reason">${esc(m.regime)} · ${esc(m.reason)}</div>`:''}</article>`}
function render(s){state=s;$('#equity').textContent=money(s.equity);let total=(s.realized||0)+(s.unrealized||0);$('#pnl').textContent=`${money(total)} session P/L`;$('#pnl').style.color=total<0?'var(--red)':'var(--green)';$('#balance').textContent=money(s.balance);$('#open').textContent=`${s.open_positions}/${s.max_positions}`;$('#realized').textContent=money(s.realized);$('#neural').textContent=`${s.neural?.samples||0} samples`;$('#status').textContent=s.status;$('#cloud-state').textContent=`CLOUD LIVE · ${new Date(s.updated_at*1000).toLocaleTimeString()}`;$('#ai-orb').classList.toggle('live',s.enabled);$('#ai-orb small').textContent=s.enabled?'ACTIVE':'PAUSED';$('#capital').value=Math.round(s.balance);$('#top-markets').innerHTML=s.markets.slice(0,5).map(m=>marketCard(m)).join('');drawMarkets();$('#position-list').innerHTML=s.positions.map(p=>`<article class="position"><div><div class="symbol">${esc(p.symbol)} · ${esc(p.side)}</div><div class="meta">${p.lots} lots · ${p.bars_open} bars</div></div><div class="score"><b class="${p.unrealized<0?'sell':'buy'}">${money(p.unrealized)}</b><small>OPEN P/L</small></div></article>`).join('');$('#trade-list').innerHTML=s.trades.map(t=>`<article class="trade"><div><div class="symbol">${esc(t.symbol)} · ${esc(t.side)}</div><div class="meta">${esc(t.reason)}</div></div><div class="score"><b class="${t.pnl<0?'sell':'buy'}">${money(t.pnl)}</b><small>${Number(t.r_multiple).toFixed(2)}R</small></div></article>`).join('')}
function drawMarkets(){if(!state)return;let q=$('#search').value.toLowerCase();$('#market-list').innerHTML=state.markets.filter(m=>`${m.symbol} ${m.name} ${m.category}`.toLowerCase().includes(q)).map(m=>marketCard(m)).join('')}
async function refresh(){try{render(await api('/api/state'));$('#login').hidden=true;$('#app').hidden=false;$('#login-error').textContent=''}catch(e){if(e.message==='Wrong access token'){clearInterval(timer);$('#app').hidden=true;$('#login').hidden=false;$('#login-error').textContent=e.message}else{$('#cloud-state').textContent='RECONNECTING…'}}}
async function control(action,extra={}){try{await api('/api/control',{method:'POST',body:JSON.stringify({action,...extra})});setTimeout(refresh,250)}catch(e){alert(e.message)}}
$('#connect').onclick=()=>{token=$('#token').value.trim();localStorage.setItem('fxai_token',token);refresh();timer=setInterval(refresh,3000)};$('#token').value=token;$('#reload').onclick=refresh;$('#start').onclick=()=>control('start');$('#pause').onclick=()=>control('pause');$('#close-all').onclick=()=>confirm('Close every open PAPER position?')&&control('close_all');$('#new-session').onclick=()=>confirm('Reset paper balance and open positions?')&&control('new_session',{capital:Number($('#capital').value)});$('#search').oninput=drawMarkets;$('#logout').onclick=()=>{localStorage.removeItem('fxai_token');location.reload()};$$('nav button').forEach(b=>b.onclick=()=>{$$('.page,nav button').forEach(x=>x.classList.remove('active'));$(`#${b.dataset.page}`).classList.add('active');b.classList.add('active')});if(token){refresh();timer=setInterval(refresh,3000)}
