'use strict';
const $=id=>document.getElementById(id);
const pages=['dashboard','markets','positions','decisions','trades','replay','performance','shadow','quality','settings'];
const names={dashboard:'Command Center',markets:'Market Scanner',positions:'Open Positions',decisions:'AI Decision Feed',trades:'Trade Log',replay:'Trade Replay',performance:'Performance Lab',shadow:'Shadow Lab',quality:'Data Quality',settings:'Settings'};
const app={token:sessionStorage.getItem('fx_token')||'',state:null,page:'dashboard',chartSymbol:'',candles:[],replay:null,replayTrade:'',requesting:false,lastCandleAt:0,noticeTimer:null,manualSelected:null};
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,n=2)=>(Number.isFinite(Number(v))?Number(v).toLocaleString('en-US',{minimumFractionDigits:n,maximumFractionDigits:n}):'—');
const money=v=>`${Number(v)<0?'-':''}$${num(Math.abs(Number(v)),2)}`;
const cls=v=>Number(v)>0?'positive':Number(v)<0?'negative':'';
const stamp=s=>{if(!s)return '—';let d=new Date(s);return Number.isNaN(d.getTime())?String(s):d.toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})};
const ptag=action=>`<span class="tag ${escape(String(action||'WAIT').toLowerCase())}">${escape(action||'WAIT')}</span>`;
const row=(left,right,sub='')=>`<div class="data-row"><div class="left"><strong>${escape(left)}</strong>${sub?`<small>${escape(sub)}</small>`:''}</div><div class="right">${right}</div></div>`;
const kv=(k,v)=>`<div class="stat-field"><small>${escape(k)}</small><strong>${escape(v)}</strong></div>`;
const metric=(label,value,sub='',color='')=>`<div class="metric"><label>${escape(label)}</label><strong class="${color}">${escape(value)}</strong><small>${escape(sub)}</small></div>`;
function toast(message,error=false){const el=$('notice');el.className=error?'error':'';el.textContent=message;clearTimeout(app.noticeTimer);app.noticeTimer=setTimeout(()=>{el.textContent=''},6500)}
async function api(path,options={}){let response=await fetch(path,{...options,headers:{'Authorization':`Bearer ${app.token}`,...(options.body?{'Content-Type':'application/json'}:{})},cache:'no-store'});let data;try{data=await response.json()}catch{throw Error(`Server responded ${response.status}`)}if(!response.ok){if(response.status===401)logout();throw Error(data.error||`HTTP ${response.status}`)}return data}
function logout(){app.token='';sessionStorage.removeItem('fx_token');$('app').hidden=true;$('login').hidden=false}
async function connect(){app.token=$('token').value.trim();$('connect').disabled=true;$('login-error').textContent='';try{app.state=await api('/api/state');sessionStorage.setItem('fx_token',app.token);$('login').hidden=true;$('app').hidden=false;initPage();render()}catch(e){$('login-error').textContent=e.message}finally{$('connect').disabled=false}}
async function fetchState(silent=true){if(app.requesting||$('app').hidden)return;app.requesting=true;try{app.state=await api('/api/state');render();if(app.page==='markets'&&app.chartSymbol&&Date.now()-app.lastCandleAt>15000)await fetchCandles()}catch(e){if(!silent)toast(e.message,true);else $('engine-status').textContent='OFFLINE'}finally{app.requesting=false}}
async function cmd(name,payload={}){try{let result=await api('/api/command/'+name,{method:'POST',body:JSON.stringify(payload)});toast(result.message||'Completed');await fetchState(false)}catch(e){toast(e.message,true)}}
function confirmDialog(title,message,yes,action='Confirm'){return new Promise(resolve=>{let el=$('confirm');$('confirm-title').textContent=title;$('confirm-message').textContent=message;$('confirm-ok').textContent=action;el.hidden=false;const done=answer=>{el.hidden=true;$('confirm-ok').onclick=null;$('confirm-cancel').onclick=null;resolve(answer)};$('confirm-ok').onclick=()=>done(true);$('confirm-cancel').onclick=()=>done(false)})}
function navigate(page){if(!pages.includes(page))return;app.page=page;document.querySelectorAll('.page').forEach(e=>e.classList.toggle('active',e.id===page));document.querySelectorAll('.nav-item[data-page]').forEach(e=>e.classList.toggle('active',e.dataset.page===page));$('page-title').textContent=names[page];$('more-menu').hidden=true;window.scrollTo({top:0,behavior:'instant'});render();if(page==='markets')fetchCandles();if(page==='replay')fetchReplay()}
function initPage(){document.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.page)));$('more-nav').onclick=()=>{$('more-menu').hidden=!$('more-menu').hidden};$('refresh').onclick=()=>fetchState(false);$('start').onclick=async()=>{if(app.state?.running)return;if(await confirmDialog('Start PAPER AI','Start the trading engine? This will open only simulated trades.','yes'))cmd('start')};$('pause').onclick=()=>cmd('pause');$('stop').onclick=async()=>{if(await confirmDialog('Stop AI','Stop opening new positions and KEEP any open PAPER trades?','yes','Keep positions'))cmd('stop',{close_positions:false});else if(await confirmDialog('Stop and close ALL?','Close every open PAPER trade and stop the engine?','yes','Close all'))cmd('stop',{close_positions:true})};$('close-all').onclick=async()=>{if(await confirmDialog('Close all PAPER trades?','This closes the simulated positions at the latest cached prices. AI must be paused.','yes','Close all'))cmd('close-all')};$('new-session').onclick=async()=>{if(await confirmDialog('Reset PAPER session?','Clear visible session P&L and start with configured capital. Requires AI paused and zero open positions.','yes','Reset session'))cmd('new-session')};$('market-search').oninput=renderMarkets;$('market-filter').onchange=renderMarkets;$('decision-filter').onchange=renderDecisions;$('replay-select').onchange=e=>{app.replayTrade=e.target.value;fetchReplay()};$('settings-form').onsubmit=saveSettings;$('disconnect').onclick=logout;$('watch-search').oninput=renderWatchlist;$('watch-save').onclick=()=>cmd('manual-symbols',{symbols:app.manualSelected||[]});window.addEventListener('resize',()=>{if(app.state)drawGraphs()});}
function render(){const s=app.state;if(!s)return;$('status-dot').classList.toggle('active',s.running);$('engine-status').textContent=s.running?'AI ACTIVE':'AI PAUSED';$('version').textContent='v'+s.version;$('about-version').textContent=s.version;$('scan-clock').textContent='Scan '+stamp(s.last_scan_at);$('engine-message').textContent=s.last_scan_error?`SCAN ERROR: ${s.last_scan_error}`:((s.market_data_mode==='LIVE' && (s.feed_diagnostics?.ready||0)===0)?'NO LIVE MARKET DATA · AI stays paused until valid candles arrive. Check Data Quality for provider errors.':s.status);$('start').disabled=!!s.running || (s.market_data_mode==='LIVE' && (s.feed_diagnostics?.ready||0)===0);$('pause').disabled=!s.running;$('open-count').textContent=s.positions.length;$('market-count').textContent=(s.feed_diagnostics?.ready||0)+' live / '+s.markets.length+' markets';$('session-label').textContent=s.markets.find(x=>x.session)?.session||'—';renderDashboard();if(app.page==='markets')renderMarkets();if(app.page==='positions')renderPositions();if(app.page==='decisions')renderDecisions();if(app.page==='trades')renderTrades();if(app.page==='replay')renderReplayList();if(app.page==='performance')renderPerformance();if(app.page==='shadow')renderShadow();if(app.page==='quality')renderQuality();if(app.page==='settings'){if(!document.activeElement?.closest?.('#settings-form'))renderSettings();renderWatchlist()}drawGraphs()}
function renderDashboard(){let s=app.state,p=s.performance;
 $('metrics').innerHTML=metric('PAPER equity',money(s.equity),'Balance '+money(s.balance))+metric('Unrealized P&L',money(s.unrealized),'Open simulated trades',cls(s.unrealized))+metric('Realized P&L',money(p.pnl),p.trades+' closed trades',cls(p.pnl))+metric('Win rate',num(p.win_rate,1)+'%',`Profit factor ${num(p.pf)}`,p.win_rate>=50?'positive':'gold');
 let risk=s.risk||{}, sel=s.selection||{};
 $('health').innerHTML=row('Live market data',`${s.feed_diagnostics?.ready||0} / ${s.feed_diagnostics?.configured||s.symbols.length}`,`${s.feed_diagnostics?.provider_errors||0} provider errors · ${s.feed_diagnostics?.fetch_attempts||0} fetch attempts`)+row('Active positions',String(s.positions.length),'Max '+s.settings.max_open_positions)+row('Selected markets',`${sel.selected_count||0} / ${sel.scanned||0}`,`${sel.eligible_count||0} eligible · ${sel.trade_ready||0} trade-ready`)+row('Drawdown',num(risk.drawdown_pct)+'%',risk.drawdown_mode||'NORMAL')+row('Risk state',escape(risk.risk_state||'—'),risk.loss_limit_mode||'NORMAL')+row('Last scanner',stamp(s.last_scan_at),s.market_data_mode+' input');
 $('top-markets').innerHTML=s.top_markets.map(sym=>{let m=s.markets.find(x=>x.symbol===sym);return m?row(sym,ptag(m.decision?.action)+' <span class="badge-value">'+num(m.rank,1)+'</span>',`${m.meta?.asset_class||'—'} · ${m.regime} · ${m.feed_status||'—'}`):''}).join('')||'<p class="muted">Waiting for market data…</p>';
 $('latest-decisions').innerHTML=decisionHtml(s.decisions.slice(0,5));}
function decisionHtml(items){return items.map(d=>`<div class="decision-card"><div class="decision-heading">${ptag(d.action)} <b>${escape(d.symbol)}</b> <span class="muted">Score ${num(d.score,1)} · ${num(d.confidence,0)}%</span></div><small>${stamp(d.ts)}</small><p>${escape(d.reason)}</p></div>`).join('')||'<p class="muted">No decisions yet. Feed loading or waiting for closed candles.</p>'}
function renderMarkets(){let s=app.state;if(!s)return;let query=$('market-search').value.toUpperCase(),filter=$('market-filter').value;if(!app.chartSymbol)app.chartSymbol=s.selected_chart_symbol||s.top_markets[0]||'EURUSD';let selected=s.selection||{};$('selection-details').textContent=`${selected.mode} · ${selected.eligible_count||0} eligible · ${selected.selected_count||0} selected · ${selected.trade_ready||0} trade-ready`;
 let list=s.markets.filter(m=>(m.symbol.includes(query)||String(m.meta?.name||'').toUpperCase().includes(query))&&(filter==='ALL'||m.meta?.asset_class===filter));$('markets-list').innerHTML=list.map(m=>`<button class="market-row ${app.chartSymbol===m.symbol?'selected':''}" data-symbol="${escape(m.symbol)}"><div><b>${escape(m.symbol)}</b><small>${escape(m.meta?.asset_class)} · ${escape(m.regime)} · ${escape(m.feed_status||'NO DATA')}${m.feed_error?' · '+escape(m.feed_error):''}</small></div><div class="right">${ptag(m.decision?.action)}<small>Rank ${num(m.rank,1)} · RSI ${num(m.rsi,0)}</small></div></button>`).join('')||'<p class="muted">No matching markets.</p>';
 $('markets-list').querySelectorAll('[data-symbol]').forEach(el=>el.onclick=async()=>{app.chartSymbol=el.dataset.symbol;cmd('select-chart',{symbol:app.chartSymbol});await fetchCandles();renderMarkets()});let m=s.markets.find(m=>m.symbol===app.chartSymbol);$('chart-title').textContent=app.chartSymbol+' · Candlesticks';$('chart-meta').textContent=m?.feed_status||'NO DATA';$('chart-summary').textContent=m?((m.feed_status==='NO LIVE DATA')?`${m.symbol}: ${m.feed_error||'Waiting for provider data. No synthetic candles are substituted.'}`:`${m.meta?.asset_class} · ${m.regime} · ${m.session||'—'} · ${m.decision?.action||'WAIT'} · RSI ${num(m.rsi,1)} · ${m.decision?.reason||''}`):'Waiting for data';drawCandles($('market-plot'),app.candles)}
async function fetchCandles(){if(app.page!=='markets')return;let symbol=app.chartSymbol||app.state?.selected_chart_symbol;if(!symbol)return;try{let data=await api('/api/candles?symbol='+encodeURIComponent(symbol));if(app.chartSymbol===symbol){app.candles=data.candles||[];app.lastCandleAt=Date.now();drawCandles($('market-plot'),app.candles)}}catch(e){toast(e.message,true)}}
function renderPositions(){let s=app.state;$('positions-list').innerHTML=s.positions.map(p=>row(`${p.side} · ${p.symbol}`,`<b class="${cls(p.unrealized)}">${money(p.unrealized)}</b>`,`Lots ${num(p.lots)} · Entry ${num(p.entry,5)} · SL ${num(p.stop,5)} · TP ${num(p.target,5)} · ${p.bars_open||0} bars`)).join('')||'<p class="muted">No open PAPER positions.</p>';$('exposure').textContent=JSON.stringify(s.exposure,null,2)}
function renderDecisions(){let f=$('decision-filter').value;$('decision-list').innerHTML=decisionHtml(app.state.decisions.filter(x=>f==='ALL'||x.action===f).slice(0,65))}
function renderTrades(){let s=app.state,p=s.performance;$('trade-metrics').innerHTML=metric('Closed',String(p.trades),'This session')+metric('Win rate',num(p.win_rate,1)+'%','PAPER')+metric('Net P&L',money(p.pnl),'After simulated costs',cls(p.pnl))+metric('Profit factor',num(p.pf),'Gross wins / losses');$('trades-list').innerHTML=s.trades.map(t=>`<div class="data-row"><div class="left"><strong>${escape(t.side)} ${escape(t.symbol)}</strong><small>${stamp(t.closed_at)} · ${escape(t.reason)}</small><small>${num(t.lots)} lots · Entry ${num(t.entry,5)} → Exit ${num(t.exit,5)}</small></div><div class="right"><b class="${cls(t.pnl)}">${money(t.pnl)}</b><small>${num(t.r_multiple)} R</small><button class="linkish" data-replay="${escape(t.id)}">Replay →</button></div></div>`).join('')||'<p class="muted">No closed PAPER trades this session.</p>';$('trades-list').querySelectorAll('[data-replay]').forEach(el=>el.onclick=()=>{app.replayTrade=el.dataset.replay;navigate('replay')})}
function renderReplayList(){let rows=app.state.replays||[],select=$('replay-select'),chosen=app.replayTrade;select.innerHTML=`<option value="">Select completed trade</option>`+rows.map(x=>`<option value="${escape(x.trade_id)}">${escape(x.symbol)} ${escape(x.side)} · ${stamp(x.closed_at)} · ${money(x.pnl)}</option>`).join('');if(rows.some(x=>x.trade_id===chosen))select.value=chosen;else if(!chosen&&rows.length){app.replayTrade=rows[0].trade_id;select.value=app.replayTrade}if(!rows.length)$('replay-info').innerHTML='<p class="muted">Replay appears after a PAPER trade closes and cached candles are available.</p>';if(app.replay&&app.replay.trade_id===app.replayTrade)drawReplay()}
async function fetchReplay(){if(app.page!=='replay')return;if(!app.replayTrade){renderReplayList();if(!app.replayTrade)return}let id=app.replayTrade;try{app.replay=await api('/api/replay?trade_id='+encodeURIComponent(id));if(id===app.replayTrade)drawReplay()}catch(e){toast(e.message,true)}}
function drawReplay(){let r=app.replay;if(!r)return;drawCandles($('replay-plot'),r.candles||[],r.metadata||{},r.side);$('replay-info').innerHTML='<div class="mini-stats">'+Object.entries(r.metadata||{}).filter(([k,v])=>['string','number','boolean'].includes(typeof v)).slice(0,30).map(([k,v])=>kv(k,String(v).slice(0,120))).join('')+'</div>'}
function renderPerformance(){let s=app.state,p=s.performance;$('performance-metrics').innerHTML=metric('Trades',String(p.trades),'Current session')+metric('Realized',money(p.pnl),'PAPER',cls(p.pnl))+metric('Expectancy',money(p.expectancy),'Per trade',cls(p.expectancy))+metric('Win rate',num(p.win_rate,1)+'%',`PF ${num(p.pf)}`);let l=s.lifetime;$('lifetime').innerHTML=row('Archived closed trades',String(l.trades),'Across prior runs')+row('Archived P&L',`<b class="${cls(l.pnl)}">${money(l.pnl)}</b>`,'Research history');}
function renderShadow(){let s=app.state;$('neural-stats').innerHTML=statObject(s.neural);$('rsi-stats').innerHTML=statObject(s.adaptive_rsi);let l={...s.risk};delete l.neural_edge;delete l.adaptive_rsi_shadow;$('learning-stats').innerHTML=statObject(l,35)}
function statObject(obj,max=20){return '<div class="mini-stats">'+Object.entries(obj||{}).filter(([,v])=>v===null||['string','number','boolean'].includes(typeof v)).slice(0,max).map(([k,v])=>kv(k.replaceAll('_',' '),typeof v==='number'?num(v,3):String(v))).join('')+'</div>'}
function renderQuality(){
 let s=app.state,by={},d=s.feed_diagnostics||{};
 s.markets.forEach(m=>{let key=m.feed_status||'NO DATA';by[key]=(by[key]||0)+1});
 let diagnostic='<p class="feed-summary">LIVE feed: '+(d.ready||0)+' / '+(d.configured||s.symbols.length)+' symbols · '+(d.provider_errors||0)+' errors · '+(d.fetch_attempts||0)+' attempted · scan worker '+(d.scan_worker_alive?'running':'NOT RUNNING')+' · '+(d.completed_scans||0)+' scans</p>';
 let errors=(d.sample_errors||[]).map(e=>row(e.symbol,'<span class="negative">Provider error</span>',escape(e.reason))).join('');
 $('quality-list').innerHTML=diagnostic+'<p class="feed-summary">'+Object.entries(by).map(([k,v])=>escape(k)+': '+v).join(' · ')+'</p>'+(errors?'<h3>Provider diagnostics</h3>'+errors:'')+s.markets.map(m=>row(m.symbol,`<span class="${m.feed_status==='LIVE'?'positive':'gold'}">${escape(m.feed_status||'NO DATA')}</span>`,`${escape(m.feed_provider||'—')} · ${m.feed_error?escape(m.feed_error):'age '+num(m.data_age_seconds||0,0)+'s · quality '+num(m.quality||0,0)+'%'}`)).join('');
 $('risk-details').innerHTML=statObject(s.risk,35);
}

const fields=[['paper_trading_capital','Paper capital (USD)'],['selection_mode','Market selection'],['market_scan_top_n','Top market count'],['risk_per_trade_pct','Max risk / trade (%)'],['max_total_risk_pct','Max combined risk (%)'],['max_open_positions','Max open positions'],['min_signal_score','Min AI score'],['trading_profile','Trading profile'],['allow_asia_session','Allow Asia'],['allow_london_session','Allow London'],['allow_new_york_session','Allow New York'],['allow_overlap_session','Allow overlap'],['allow_rollover_session','Allow rollover (high risk)'],['self_learning_enabled','Self-learning'],['counterfactual_learning_enabled','Shadow counterfactuals']];

function renderWatchlist(){let s=app.state;if(!s)return;if(!app.manualSelected)app.manualSelected=[...(s.manual_selected_symbols||[])];let q=$('watch-search').value.trim().toUpperCase();$('watch-selected').textContent=app.manualSelected.length+' selected: '+app.manualSelected.join(', ');$('watch-list').innerHTML=s.symbols.filter(x=>!q||x.includes(q)).slice(0,70).map(sym=>`<button type="button" class="market-row ${app.manualSelected.includes(sym)?'selected':''}" data-watch="${escape(sym)}"><span>${escape(sym)}</span><span class="tag">${app.manualSelected.includes(sym)?'✓ INCLUDED':'ADD +'}</span></button>`).join('');$('watch-list').querySelectorAll('button').forEach(el=>el.onclick=()=>{let sym=el.dataset.watch,index=app.manualSelected.indexOf(sym);if(index>=0)app.manualSelected.splice(index,1);else if(app.manualSelected.length<25)app.manualSelected.push(sym);else return toast('25 markets maximum',true);renderWatchlist()})}
function renderSettings(){let s=app.state.settings;$('settings-fields').innerHTML=fields.map(([key,label])=>{let val=s[key],input=typeof val==='boolean'?`<input type="checkbox" name="${key}" ${val?'checked':''}>`:key==='selection_mode'?`<select name="${key}">${['AUTO TOP 5','AUTO TOP 10','MANUAL'].map(v=>`<option ${val===v?'selected':''}>${v}</option>`).join('')}</select>`:key==='trading_profile'?`<select name="${key}">${['AI TRADING','MANUAL'].map(v=>`<option ${val===v?'selected':''}>${v}</option>`).join('')}</select>`:`<input type="number" name="${key}" value="${escape(val)}" step="${Number.isInteger(val)?1:0.01}">`;return `<div class="form-field"><label for="field-${key}">${escape(label)}</label>${input.replace(' name=',` id="field-${key}" name=`)}</div>`}).join('')}
async function saveSettings(e){e.preventDefault();let obj={},form=new FormData(e.target);for(const [key,val] of fields){let old=app.state.settings[key],input=e.target.elements.namedItem(key);obj[key]=typeof old==='boolean'?input.checked:typeof old==='number'?Number(form.get(key)):form.get(key)}await cmd('settings',{values:obj})}
function drawGraphs(){let s=app.state;if(!s)return;drawLine($('equity-plot'),s.equity_history.map(v=>v.equity));if(app.page==='performance')drawLine($('performance-plot'),s.equity_history.map(v=>v.equity));if(app.page==='markets')drawCandles($('market-plot'),app.candles);if(app.page==='replay'&&app.replay)drawReplay()}
function setupCanvas(canvas){if(!canvas||canvas.closest('.page')?.classList.contains('active')===false)return null;let w=Math.max(200,canvas.clientWidth),h=Number(canvas.getAttribute('height'))||200;let dpi=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(w*dpi);canvas.height=Math.round(h*dpi);let ctx=canvas.getContext('2d');ctx.scale(dpi,dpi);ctx.clearRect(0,0,w,h);return {ctx,w,h}}
function emptyGraph(ctx,w,h,text){ctx.fillStyle='#7389a3';ctx.textAlign='center';ctx.font='12px system-ui';ctx.fillText(text,w/2,h/2)}
function drawLine(el,values){let c=setupCanvas(el);if(!c)return;let {ctx,w,h}=c;values=values.filter(v=>Number.isFinite(Number(v))).map(Number);if(values.length<2){emptyGraph(ctx,w,h,'Waiting for equity history');return}let min=Math.min(...values),max=Math.max(...values),span=Math.max(max-min,Math.abs(max)*0.0005,1);min-=span*.12;max+=span*.12;const x=i=>18+i*(w-35)/(values.length-1),y=v=>h-23-(v-min)/(max-min)*(h-43);ctx.strokeStyle='#283d54';ctx.lineWidth=1;for(let i=0;i<4;i++){let yy=20+i*(h-43)/3;ctx.beginPath();ctx.moveTo(15,yy);ctx.lineTo(w-12,yy);ctx.stroke()}ctx.beginPath();values.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.lineWidth=2.4;ctx.strokeStyle=values.at(-1)>=values[0]?'#43d2a2':'#f36d79';ctx.stroke();ctx.fillStyle='#a5b9cf';ctx.font='11px system-ui';ctx.fillText('$'+num(values.at(-1),0),12,15)}
function drawCandles(el,candles,markers=null,tradeSide='BUY'){let c=setupCanvas(el);if(!c)return;let {ctx,w,h}=c;let data=(candles||[]).filter(x=>['open','high','low','close'].every(k=>Number.isFinite(Number(x[k]))));if(data.length<2){emptyGraph(ctx,w,h,'Waiting for REAL OHLC candle data');return}data=data.slice(-Math.max(20,Math.min(100,Math.floor(w/6))));let lo=Math.min(...data.map(c=>Number(c.low))),hi=Math.max(...data.map(c=>Number(c.high)));let padding=(hi-lo)*.12||Math.max(hi*.001,.0001);lo-=padding;hi+=padding;let x=i=>16+(i+.5)*(w-60)/data.length,y=v=>h-25-(v-lo)/(hi-lo)*(h-47);ctx.font='10px system-ui';ctx.strokeStyle='#23364b';for(let i=0;i<5;i++){let yy=15+i*(h-43)/4;ctx.beginPath();ctx.moveTo(8,yy);ctx.lineTo(w-35,yy);ctx.stroke();ctx.fillStyle='#89a0b9';ctx.fillText(num(hi-i*(hi-lo)/4,hi<10?4:2),w-37,yy-3)}let cw=Math.max(2,(w-60)/data.length*.62);data.forEach((c,i)=>{let xx=x(i),up=+c.close>=+c.open;ctx.strokeStyle=up?'#42c89d':'#eb6474';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(xx,y(c.high));ctx.lineTo(xx,y(c.low));ctx.stroke();let a=y(c.open),b=y(c.close);ctx.fillRect(xx-cw/2,Math.min(a,b),cw,Math.max(1,Math.abs(a-b)))});
 if(markers){let met=markers||{};let levels=[['entry', '#e7bd56'],['exit','#a6b6cf'],['initial_stop','#f36d79'],['initial_target','#43d2a2'],['final_stop','#f9b96b']];for(let [key,color]of levels){let v=Number(met[key]??met[key+'_price']);if(!Number.isFinite(v)||v<lo||v>hi)continue;let yy=y(v);ctx.setLineDash([4,3]);ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(12,yy);ctx.lineTo(w-40,yy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=color;ctx.font='10px system-ui';ctx.fillText(({entry:tradeSide+' ENTRY',exit:(tradeSide==='BUY'?'SELL':'BUY')+' EXIT',initial_stop:'SL',initial_target:'TP',final_stop:'FINAL SL'}[key]||key),17,Math.max(13,yy-3))}
 let epoch=t=>{let a=Date.parse(t);return Number.isFinite(a)?a/1000:null};let markersToDraw=[['opened_at',markers.entry,tradeSide+' ENTRY',tradeSide==='BUY'?'#43d2a2':'#f36d79'],['closed_at',markers.exit,(tradeSide==='BUY'?'SELL':'BUY')+' EXIT','#e7bd56']];for(let [key,price,label,color]of markersToDraw){let ts=epoch(markers[key]);if(!ts||!Number.isFinite(Number(price)))continue;let i=data.reduce((best,x,idx)=>Math.abs(Number(x.ts)-ts)<Math.abs(Number(data[best].ts)-ts)?idx:best,0),xx=x(i),yy=y(Number(price));ctx.strokeStyle=color;ctx.lineWidth=2;ctx.strokeRect(xx-cw/2-3,12,cw+6,h-40);ctx.fillStyle=color;ctx.beginPath();ctx.arc(xx,yy,5.5,0,Math.PI*2);ctx.fill();ctx.fillText(label,Math.max(10,Math.min(w-115,xx+8)),Math.max(15,Math.min(h-16,yy-10)))}}
}
$('connect').onclick=connect;$('token').onkeydown=e=>{if(e.key==='Enter')connect()};if(app.token){$('token').value=app.token;connect()}setInterval(()=>{if(!$('app').hidden)fetchState()},5000);
